{
 "title": "HS110 Workstation",
 "tags": [ "hs110" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "HS110",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "sum(hs110_power_watt)", "legendFormat": "Watt" },
    { "expr": "sum(hs110_voltage)", "legendFormat": "Volt" }
   ]
  },
  {
   "title": "kWatt in rage",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 0 },
   "format": "kwatt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(avg_over_time(hs110_power_watt[1h])/1000)",
     "legendFormat": "kW"
    }
   ]
  },
  {
   "title": "W/hora",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "currencyEUR" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(hs110_power_watt[1h])/1000)*0.0908 and (hour() > 21 or hour() <= 11)",
     "legendFormat": "Night"
    },
    {
     "expr": "sum(avg_over_time(hs110_power_watt[1h])/1000)*0.1684 and hour() > 11 and hour() <=21",
     "legendFormat": "Day"
    }
   ]
  },
  {
   "title": "Cost in range",
   "type": "singlestat",
   "description": "Tarifa nocturna",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 2 },
   "format": "currencyEUR",
   "valueName": "total",
   "targets": [
    {
     "expr": "(sum(avg_over_time(hs110_power_watt[1h])/1000)*0.0908 and (hour() > 21 or hour() <= 11))\r\nor\r\n(sum(avg_over_time(hs110_power_watt[1h])/1000)*0.1684 and hour() > 11 and hour() <=21)",
     "legendFormat": "Euro"
    }
   ]
  }
 ]
}